language: python
python:
  - "3.8"
services:
  - docker
install: skip
jobs:
  include:
    - name: Build docker image
      script:
        - docker-compose build tests
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push "securetrading1/py-payments-testing"