version: "3.6"
services:
  app:
    image: securetrading1/js-payments:${APP_BRANCH}
    ports:
      - 8443:8443
    networks:
      securetrading:
        aliases:
          - merchant.example.com
  tests:
    build: .
    volumes:
      - .:/app
    networks:
      - securetrading

  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8080:8080
    networks:
      securetrading:
        aliases:
          - webservices.securetrading.net

networks:
  securetrading:
    driver: bridge
