version: "3.6"
services:
  app:
    image: securetrading1/js-payments:${APP_BRANCH}
    networks:
      securetrading:
        aliases:
          - merchant.example.com
  tests:
    build: .
    volumes:
      - .:/app
    networks:
      - securetrading

  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    command: --https-port 8443
    networks:
      securetrading:
        aliases:
          - webservices.securetrading.net

networks:
  securetrading:
    driver: bridge
