version: "3.6"
services:
  app:
    image: securetrading1/js-payments:${APP_BRANCH}
    networks:
      securetrading:
        aliases:
          - library.securetrading.net

  tests:
    build: .
    image: securetrading1/py-payments-testing
    volumes:
      - .:/app
    networks:
      - securetrading

  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/keystore:/home/wiremock/keystore
    command: --https-port 8443 --https-keystore /home/wiremock/keystore
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      securetrading:
        aliases:
          - webservices.securetrading.net

  example:
    image: nginx:1.16.1
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./example/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./example/nginx/key.pem:/etc/ssl/st-cert/key.pem
      - ./example/nginx/cert.pem:/etc/ssl/st-cert/cert.pem
      - ./example/html:/usr/share/nginx/html
    networks:
      securetrading:
        aliases:
          - merchant.example.com

networks:
  securetrading:
    driver: bridge
