version: "3.6"
services:
  app:
    image: securetrading1/${APP_REPO}:${APP_BRANCH}
    ports:
      - 80:80
      - 443:443
    networks:
      securetrading:
        aliases:
          - library.securetrading.net
          - merchant.securetrading.net

  tests:
    build: .
    image: securetrading1/py-payments-testing
    volumes:
      - .:/app
    networks:
      - securetrading

  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/keystore:/home/wiremock/keystore
    command: --https-port 8443 --https-keystore /home/wiremock/keystore
    ports:
      - 8443:8443
    networks:
      securetrading:
        aliases:
          - webservices.securetrading.net

networks:
  securetrading:
    driver: bridge
