from enum import Enum


class Config(Enum):
    BASE_CONFIG = "config.json"
    SUBMIT_ON_SUCCESS_TRUE = "configSubmitOnSuccessTrue.json"
    SUBMIT_ON_ERROR_TRUE = "configSubmitOnErrorTrue.json"
    SUBMIT_ON_CANCEL_TRUE = "configSubmitOnCancelTrue.json"
    SUBMIT_ON_SUCCESS_AND_ERROR_TRUE = "configSubmitOnSuccessAndErrorTrue.json"
    ANIMATED_CARD = "configAnimatedCardTrue.json"
    UPDATE_JWT = "configUpdateJwtTrue.json"
    FIELD_STYLE = "configFieldStyle.json"
    IMMEDIATE_PAYMENT = "configImmediatePayment.json"
    IMMEDIATE_PAYMENT_SUBMIT_ON_SUCCESS = "configImmediatePaymentAndSubmitOnSuccess.json"
    SKIP_JSINIT = "configSkipJSinit.json"
    DEFER_INIT = "configDeferInitTrue.json"
    SUBMIT_CVV_ONLY = "configSubmitCvvOnly.json"
    SUBMIT_CVV_FOR_AMEX = "configSubmitCvvForAmex.json"
    SUBMIT_CVV_TO_SUBMIT_AND_SUBMIT_ON_SUCCESS = "configSubmitCvvAndSubmitOnSuccess.json"
    BYPASS_CARDS = "configBypassCards.json"
    INCORRECT_REQUEST_TYPE = "configIncorrectRequestType.json"
    PLACEHOLDERS = "configPlaceholders.json"
    NOTIFICATIONS_FALSE = "configNotificationsFalse.json"
    CYBERTONICA = "configCybertonica.json"
    CYBERTONICA_BYPASS_CARD = "configCybertonicaBypassCards.json"
    CYBERTONICA_IMMEDIATE_PAYMENT = "configCybertonicaImmediatePayment.json"
